workflow:
  cron-producer: "producer"
  cron-consumer: "consumer"

temporal:
  host: "10.96.144.66:7233"
  taskqueue: "cron"

kafka:
#  host: "127.0.0.1:31027"
  host: "10.96.236.44:9092"

  topic: "topic1"
  consumer-group: "consumer-group-1"