---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: temporal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /temporal(/|$)
            backend:
              service:
                name: temporaltest-web
                port:
                  number: 8080